apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-servicemonitor
  labels:
    app: web
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: web
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
